# Generated by Django 4.0.4 on 2025-08-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spend_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='payment_method',
            field=models.CharField(choices=[('cash', '現金'), ('card', '信用卡'), ('Apple Pay', 'Apple Pay'), ('Line Pay', 'Line Pay'), ('bank', '匯款'), ('other', '其他')], default='cash', max_length=20),
        ),
    ]
